# Generated by Django 3.2.7 on 2021-09-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vscwebnjiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultModel',
            new_name='NjiroresultModel',
        ),
    ]
