# Generated by Django 3.2.7 on 2021-09-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vscwebnjiro', '0002_rename_resultmodel_njiroresultmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NjiroresultModel',
            new_name='ResultModel',
        ),
    ]
